version: '3'

services:
  db:
    image: mariadb:latest
    container_name: some-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: nextcloud

  nextcloud:
    image: nextcloud:latest
    container_name: some-nextcloud
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
